### ISSUE TITLE
Upgrade to 4.5.1? Thank you.

### ISSUE THREAD

**Issue by sebastienbarre** [alisamar/react-icons-all-files#1]
Thanks for your work exposing all icons in one package.

The official [@react-icons/all-files - npm](https://www.npmjs.com/package/@react-icons/all-files) is still stuck on 4.1.0

I was wondering if you had any plans on upgrading your package from 4.3.1 to 4.5.1?
A lot of good icons were added since 4.3.1, including the whole Tabler and Heroicons 2 collections.

Thank you very much

**Comment by alisamar** [comment]
Hi Sebastian, I just released the latest version(4.5.1), you can upgrade now.

Thank you

**Comment by sebastienbarre** [comment]
Beautiful, thanks.
